import { Manrope } from 'next/font/google'
import './globals.css'

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
  variable: '--font-manrope'
})

export const metadata = {
  title: 'Telegram Web App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className={manrope.variable} lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}
