import Script from 'next/script'
import { Manrope } from 'next/font/google'
import Providers from './providers'
import './globals.css'

const manrope = Manrope({
  subsets: ['latin'],
  weight: ['400', '600', '700'],
  display: 'swap',
  variable: '--font-manrope'
})

export const metadata = {
  title: 'Telegram Web App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html className={manrope.variable} lang="en" suppressHydrationWarning>
      <head>
        <Script src="https://telegram.org/js/telegram-web-app.js" strategy="beforeInteractive" />
      </head>
      <body>
        <Providers>
          <main className="wrapper">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  )
}
